on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        php_version:
          - 7.4.5
          - 7.3.17
          - 7.2.30
          - 7.1.33
          - 7.0.33
          - 5.6.40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        